export const FIND_ALL_USER = "FIND_ALL_USER";
export const FIND_ONE_USER = "FIND_ONE_USER";

// reducer type
export const USERDETAILS_LOADING = "USERDETAILS_LOADING";
export const USERDETAILS_LOADED = "USERDETAILS_LOADED";
export const USERDETAILS_FAILED = "USERDETAILS_FAILED";
